server:
  port: 5555
 
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: app
        uri: lb://EUREKA-APP-CLIENT
        predicates:
        - Path=/app/**
    discovery:
      enabled: true
