package com.ezyxip.pcmback.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "CPU")
public class CPUEntity {
    @Id
    @Autogenerated
    private Long id;
    private String model;
    private String brand;
    private String core;
    private String socket;
    private int coreNum;
    private int streamNum;
    private int frequency;
    private int L1;
    private int L2;
    private int L3;
    private int calculationCapacity;
    private int Factor;
    private int technicalProcess;
    private int heatDissipation;
    private int maxTemp;
    private String processorGeneration;
    private int maxMemoryCapacity;
    private  ArrayList<Pair<String, boolean>> memoryType;
    private ArrayList<Pair<String, int>>  memoryFrequencySupport;
    private int memoryChannelsNum;
    private int memoryBandwidth;
    private String PCIExpressVersion;
    private int PCIExpressChannelNum;

    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getModel() {
        return model;
    }
    public void setModel(String model) {
        this.model = model;
    }
    public String getBrand() {
        return brand;
    }
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getCore() {
        return core;
    }
    public void setCore(String core) {
        this.core = core;
    }
    public String getSocket() {
        return socket;
    }
    public void setSocket(String socket) {
        this.socket = socket;
    }
    public int getCoreNum() {
        return coreNum;
    }
    public void setCoreNum(int coreNum) {
        this.coreNum = coreNum;
    }
    public int getStreamNum() {
        return streamNum;
    }
    public void setStreamNum(int streamNum) {
        this.streamNum = streamNum;
    }
    public int getFrequency() {
        return frequency;
    }
    public void setFrequency(int frequency) {
        this.frequency = frequency;
    }
    public int getL1() {
        return L1;
    }
    public void setL1(int l1) {
        L1 = l1;
    }
    public int getL2() {
        return L2;
    }
    public void setL2(int l2) {
        L2 = l2;
    }
    public int getL3() {
        return L3;
    }
    public void setL3(int l3) {
        L3 = l3;
    }
    public int getCalculationCapacity() {
        return calculationCapacity;
    }
    public void setCalculationCapacity(int calculationCapacity) {
        this.calculationCapacity = calculationCapacity;
    }
    public int getFactor() {
        return Factor;
    }
    public void setFactor(int factor) {
        Factor = factor;
    }
    public int getTechnicalProcess() {
        return technicalProcess;
    }
    public void setTechnicalProcess(int technicalProcess) {
        this.technicalProcess = technicalProcess;
    }
    public int getHeatDissipation() {
        return heatDissipation;
    }
    public void setHeatDissipation(int heatDissipation) {
        this.heatDissipation = heatDissipation;
    }
    public int getMaxTemp() {
        return maxTemp;
    }
    public void setMaxTemp(int maxTemp) {
        this.maxTemp = maxTemp;
    }
    public String getProcessorGeneration() {
        return processorGeneration;
    }
    public void setProcessorGeneration(String processorGeneration) {
        this.processorGeneration = processorGeneration;
    }
    public int getMaxMemoryCapacity() {
        return maxMemoryCapacity;
    }
    public void setMaxMemoryCapacity(int maxMemoryCapacity) {
        this.maxMemoryCapacity = maxMemoryCapacity;
    }
    public ArrayList<Pair<String, boolean>> getMemoryType() {
        return memoryType;
    }
    public void setMemoryType(ArrayList<Pair<String, boolean>> memoryType) {
        this.memoryType = memoryType;
    }
    public ArrayList<Pair<String, int>> getMemoryFrequencySupport() {
        return memoryFrequencySupport;
    }
    public void setMemoryFrequencySupport(ArrayList<Pair<String, int>> memoryFrequencySupport) {
        this.memoryFrequencySupport = memoryFrequencySupport;
    }
    public int getMemoryChannelsNum() {
        return memoryChannelsNum;
    }
    public void setMemoryChannelsNum(int memoryChannelsNum) {
        this.memoryChannelsNum = memoryChannelsNum;
    }

    @Override
    public String toString() {
        return "";
    }
}