package com.ezyxip.pcmback.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "HDD")
public class OPEntity {
    @Id
    @Autogenerated
    private Long id;
    private String model;
    private String brand;
}